4.c) SELECT p.REFERENCE_COMMANDE,p.NUMERO_LIGNE_COMMANDE,p.REFERENCE_TYPE_PIECE, COUNT(p.REFERENCE_PIECE) FROM piece p GROUP by p.REFERENCE_COMMANDE,p.NUMERO_LIGNE_COMMANDE; 
4.d) SELECT l.REFERENCE_TYPE_PIECE,SUM(l.QUANTITE_PIECES_COMMANDEES) FROM ligne_commande l GROUP BY l.REFERENCE_TYPE_PIECE;

5.a) SELECT l.REFERENCE_TYPE_PIECE,SUM(l.QUANTITE_PIECES_COMMANDEES) as 'Somme'
		from ligne_commande l 
		WHERE l.REFERENCE_TYPE_PIECE = 'AR232';

5.b) SELECT l.REFERENCE_TYPE_PIECE,SUM(l.QUANTITE_PIECES_COMMANDEES) as 'Somme'
		from ligne_commande l JOIN commande c on c.REFERENCE_COMMANDE = l.REFERENCE_COMMANDE
		WHERE l.REFERENCE_TYPE_PIECE = 'AR232'
		AND c.RAISON_SOCIALE = 'PEUGEOT';

5.c) SELECT c.RAISON_SOCIALE, l.REFERENCE_TYPE_PIECE,SUM(l.QUANTITE_PIECES_COMMANDEES) as 'Somme'
		from ligne_commande l JOIN commande c on c.REFERENCE_COMMANDE = l.REFERENCE_COMMANDE
		WHERE l.REFERENCE_TYPE_PIECE = 'AR232'
		GROUP by c.RAISON_SOCIALE;

6.a) SELECT l.REFERENCE_COMMANDE,sum(l.QUANTITE_PIECES_COMMANDEES*l.PRIX_PIECE) as 'Somme'
		from ligne_commande l
		GROUP by l.REFERENCE_COMMANDE;
6.b) 





1)
type piece, piece
Caracteriser
Piece
SELECT P.REFERENCE_TYPE_PIECE FROM piece P GROUP BY P.REFERENCE_TYPE_PIECE; 

2)
ligne commande, piece
appartenir
Ligne commande, piece
SELECT p.REFERENCE_PIECE,l.NUMERO_LIGNE_COMMANDE, l.REFERENCE_COMMANDE FROM piece p,ligne_commande l
WHERE l.REFERENCE_COMMANDE = p.REFERENCE_COMMANDE
AND l.NUMERO_LIGNE_COMMANDE = p.NUMERO_LIGNE_COMMANDE 
AND p.REFERENCE_PIECE=212;


3)
Commande, Ligne commande, piece
Détailler, Appartenir
Piece, commande
SELECT p.REFERENCE_PIECE,c.DATE_COMMANDE FROM piece p 
JOIN commande c on c.REFERENCE_COMMANDE = p.REFERENCE_COMMANDE
WHERE p.REFERENCE_PIECE=212;

4)
Commande, ligne commande
Détailler
Ligne commande
SELECT COUNT(l.REFERENCE_COMMANDE) FROM ligne_commande l WHERE l.REFERENCE_COMMANDE = 5;

SELECT l.REFERENCE_COMMANDE, COUNT(l.REFERENCE_COMMANDE) as 'Nb Lignes'
FROM ligne_commande l
WHERE l.REFERENCE_COMMANDE = 5;